# Dump the data windows (local file offsets) of arm64-v8a .so files inside the
# release APK. Output is a ready-to-paste Dart map literal for
# kApkSoWindows in mobile/lib/onnx/socket_worker.dart.
#
# Usage:  python tool/dump_apk_so_windows.py [path\to\app-release.apk]
#
# Why: Flutter dlopens .so files directly from base.apk; in /proc/<pid>/maps
# they all share the same "base.apk" path, so a crash PC's file offset
# (pgoff + pc - map_start) must be matched against each so's data window
# inside the APK to attribute the frame to the right library.
import struct
import sys
import zipfile


def so_windows(apk_path):
    z = zipfile.ZipFile(apk_path)
    out = {}
    with open(apk_path, 'rb') as f:
        for info in z.infolist():
            name = info.filename
            if not name.startswith('lib/arm64-v8a/') or not name.endswith('.so'):
                continue
            f.seek(info.header_offset)
            hdr = f.read(30)
            sig, _ver, _flag, method, _t, _d, _crc, csize, usize, nlen, elen = \
                struct.unpack('<IHHHHHIIIHH', hdr)
            assert sig == 0x04034B50, (name, hex(sig))
            # method 0 (stored) is what gradle ships for pre-compressed .so;
            # for method 8 the window would be the compressed blob — useless
            # for attribution, so flag it loudly.
            data_off = info.header_offset + 30 + nlen + elen
            size = usize if method == 0 else csize
            out[name.split('/')[-1]] = (data_off, data_off + size, method)
    return out


def main():
    apk = sys.argv[1] if len(sys.argv) > 1 else \
        r'mobile\build\app\outputs\flutter-apk\app-release.apk'
    wins = so_windows(apk)
    print('// Generated by tool/dump_apk_so_windows.py — paste into'
          ' kApkSoWindows:')
    print('const Map<String, (int, int)> kApkSoWindows = {')
    for name in sorted(wins, key=lambda k: wins[k][0]):
        lo, hi, method = wins[name]
        suffix = '' if method == 0 else '  // WARNING: method=8 (deflated)'
        print(f"  '{name}': ({lo}, {hi}),{suffix}")
    print('};')


if __name__ == '__main__':
    main()
